name: Secrets and env value call

on:
  push:
    branches:
      - main

env:
  qa: "https://qa.example.com"

jobs:
  env:
    runs-on: ubuntu-latest

    steps:
      - name: Print secret
        run: echo "API Key is ${{ secrets.API_KEY }}"

      - name: Print environment variable
        run: echo "QA URL is ${{ env.qa }}"
        
